services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      LLAMA_API_KEY: ${LLAMA_API_KEY}
      LLAMA_API_URL: ${LLAMA_API_URL}